name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all tags are fetched

      - name: Find latest tag
        id: latest-tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        shell: bash

      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/app.exe
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
