[phases.setup]
nixPkgs = [
    'python39',
    'python39Packages.pip',
    'python39Packages.setuptools',
    'python39Packages.wheel',
    'gcc',
    'gcc-unwrapped',
    'stdenv.cc.cc.lib'
]

[phases.install]
cmds = [
    'python -m pip install --no-cache-dir --upgrade pip setuptools wheel',
    'python -m pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'gunicorn auth:app' 